### PR TITLE
feat: run pipelines in parallel

### PR DESCRIPTION
**Pull request by Skisocks**
It's taking an hour+ to run a pr because all the build/pushing happens in series. This PR moves each build/push into its own pipeline.

There is no nice way to do parallel pipelines in our current version of tekton so this will have to do for the time being.

### CODE REVIEW

**Comment by Skisocks** [comment]
/override pr

PR pipe doesn't exist anymore - it's just being cached

**Comment by Skisocks** [comment]
/override pr

Same same

**Comment by Skisocks** [comment]
/override pr

Same same

**Review by mentlak0 — APPROVED** [review]
LGTM

**Pull request merged**
